/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "interface2.h"

bool_t
xdr_nodo_Alertas2 (XDR *xdrs, nodo_Alertas2 *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->fecha, MEDCADENA,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->hora, MEDCADENA,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->puntuacion))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nodo_Indicadores2 (XDR *xdrs, nodo_Indicadores2 *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->frecuenciaCardiaca))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->frecuenciaRespiratoria))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->temperatura))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nodo_Asintomatico2 (XDR *xdrs, nodo_Asintomatico2 *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->nombre, MAXCADENA,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->apellido, MAXCADENA,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->tipo_id, MINCADENA,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->direccion, MAXCADENA,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->ultimoIndicador))
		 return FALSE;
	 if (!xdr_nodo_Indicadores2 (xdrs, &objp->ultimoIndicador2))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->alertas, 5,
		sizeof (nodo_Alertas2), (xdrproc_t) xdr_nodo_Alertas2))
		 return FALSE;
	return TRUE;
}
