/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "interface1.h"
#include <string.h>
#include <stdbool.h>
#include <stdlib.h>/*Para el ramdon*/
// C function showing how to do time delay 
#include <stdio.h> 
// To use time library of C 
#include <time.h> 

float indicadoresRandom();
void lecturaSensores();
int analizadorAutomatico();
void delay();
int solicitudDatos();

void
gestion_alertas_1(char *host)
{
	CLIENT *clnt;
	bool_t  *result_1;
	nodo_Asintomatico  registrarasintomatico_1_arg;
	bool_t  *result_2;
	nodo_Indicadores  enviarindicadores_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, gestion_alertas, gestion_alertas_version, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	int op=0;
	int analizado = 0;/*varable que recibe la puntuacion*/
	bool pararEnvio = FALSE; /*sale del while para dejar de enviar los indicadores cada 8sg*/
	bool asintomaticoRegistrado = FALSE;
	do
	{
		printf("\n_________________________________\n");
		printf("|                                |\n");
		printf("|         MENU SENSORES          |\n");
		printf("|________________________________|\n");
		printf("|                                |\n");
		printf("|1. Registrar datos.             |\n");
		printf("|2. Comenzar lectura de sensores.|\n");
		printf("|3. Salir.                       |\n");
		printf("|________________________________|\n");
		printf("                                  \n");		
		printf("Seleccione una opcion: \n");
		scanf("%d", &op);
		
		switch(op)
		{
			case 1:
				if(asintomaticoRegistrado==FALSE){
					if(solicitudDatos(&registrarasintomatico_1_arg)==0){/*Si la informaciòn està bien, retornarà un 0*/
						result_1 = registrarasintomatico_1(&registrarasintomatico_1_arg, clnt);
						if (result_1 == (bool_t *) NULL) {
							clnt_perror (clnt, "call failed");
						}

						if(*result_1 == 0){
							strcpy(enviarindicadores_1_arg.tipo_id, registrarasintomatico_1_arg.tipo_id);/*Aquì se llena la estructura de indicadores*/
							enviarindicadores_1_arg.id = registrarasintomatico_1_arg.id;
							asintomaticoRegistrado=TRUE;
							printf("\nEl paciente %s %s con %s.%d ha quedado registrado.\n",registrarasintomatico_1_arg.nombre,registrarasintomatico_1_arg.apellido,registrarasintomatico_1_arg.tipo_id,registrarasintomatico_1_arg.id);
									
						}
						if(*result_1 == 1){
							printf("No se pudo realizar el registro.\n");	
						}			
					}

				}else{
					printf("Ya existe un paciente registrado.\n");
				}
				
				break;
			case 2:
				if(asintomaticoRegistrado==TRUE){
					while(FALSE == pararEnvio){

						delay(8000);/*Retardo de 8sg*/
						lecturaSensores(&enviarindicadores_1_arg);
						analizado = analizadorAutomatico(&enviarindicadores_1_arg);

						if(analizado <= 1){
							printf("Monitoreo normal...\n");
						}

						if(analizado >= 2){	
							printf("Enviando indicadores...\n");
							printf("Frecuencia cardiaca: %.2f\n",enviarindicadores_1_arg.frecuenciaCardiaca);
							printf("Frecuencia respiratoria: %.2f\n",enviarindicadores_1_arg.frecuenciaRespiratoria);
							printf("Temperatura: %.2f\n\n",enviarindicadores_1_arg.temperatura);
							result_2 = enviarindicadores_1(&enviarindicadores_1_arg, clnt);
							if (result_2 == (bool_t *) NULL) {
								clnt_perror (clnt, "call failed");
							}
							//pararEnvio = TRUE;
						}

					}
				}else{
					printf("Todavìa no ha registrado el paciente.\n");
				}
			break;
			case 3:
			break;
			
			default:
				printf("Opción invalida!");	
		}	
	}while(op != 3);

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	gestion_alertas_1 (host);
exit (0);
}

float indicadoresRandom(){
	float numero = drand48() * (100.0-1.0) + 1.0;	
	return numero;
}

void lecturaSensores(nodo_Indicadores *pEnviarindicadores_1_arg){
	float frecuenciaCardiaca = indicadoresRandom();
	float frecuenciaRespiratoria = indicadoresRandom();
	float temperatura = indicadoresRandom();
	/*Asignamos los ramdon a la estructura*/
	pEnviarindicadores_1_arg->frecuenciaCardiaca = frecuenciaCardiaca;
	pEnviarindicadores_1_arg->frecuenciaRespiratoria=frecuenciaRespiratoria;
	pEnviarindicadores_1_arg->temperatura=temperatura;	
}

void delay(int number_of_seconds) 
{ 
    /* Converting time into milli_seconds */
    int milli_seconds = 1000 * number_of_seconds; 
    /* Storing start time */
    clock_t start_time = clock();  
    /* looping till required time is not achieved */
    while (clock() < start_time + milli_seconds); 
} 

int analizadorAutomatico(nodo_Indicadores *pEnviarindicadores_1_arg){
	int suma = 0;
	if(pEnviarindicadores_1_arg->frecuenciaCardiaca >= 60 && pEnviarindicadores_1_arg->frecuenciaCardiaca<=80 ){
		suma++;
	}
	if(pEnviarindicadores_1_arg->frecuenciaRespiratoria >= 70 && pEnviarindicadores_1_arg->frecuenciaRespiratoria<=90 ){
		suma++;
	}
	if(pEnviarindicadores_1_arg->temperatura >= 36.2 && pEnviarindicadores_1_arg->temperatura<=37.2 ){
		suma++;
	}
	return suma;
}

int solicitudDatos(nodo_Asintomatico *pRegistrarasintomatico_1_arg){
	char pruebaid[30];
	char pruebatipoid[10];
	char pruebanombre[30];
	char pruebaapellido[30];
	char pruebadireccion[30];
	int tamanio=0;
	bool estaBien = FALSE;/*Para id*/
	bool tipoCorrecto = FALSE;
	int retorno = 1; /*Fallo*/

	printf("**********Registrar datos***********\n");
	do{
		printf("\nDigite nombre: ");
		scanf("%s", &pruebanombre);
		tamanio = strlen(pruebanombre);
		if(tamanio <= 31){/*31 con el caracter final que le pone C*/
			strcpy(pRegistrarasintomatico_1_arg->nombre, pruebanombre);
		}

	}while(tamanio > 31);

	do{
		printf("\nDigite Apellido: ");
		scanf("%s", &pruebaapellido);
		tamanio = strlen(pruebaapellido);
		if(tamanio <= 31){
			strcpy(pRegistrarasintomatico_1_arg->apellido, pruebaapellido);
		}

	}while(tamanio > 31);

	do{

		printf("\nDigite tipo de id CC/TI/PP: ");	
		scanf("%s", &pruebatipoid);
		if(strcmp(pruebatipoid, "CC") == 0 || strcmp(pruebatipoid, "TI")==0 ||  strcmp(pruebatipoid, "PP")==0){
			strcpy(pRegistrarasintomatico_1_arg->tipo_id, pruebatipoid);
			tipoCorrecto = TRUE;
		}

	}while(tipoCorrecto == FALSE);
	
	
	do{
		printf("\nDigite id: ");
		scanf("%s", &pruebaid);
		int valor = atoi(pruebaid);
		tamanio = strlen(pruebaid);
		if(valor == 0 && tamanio == 1 && strcmp(pruebaid, "0")==0){
			pRegistrarasintomatico_1_arg->id=valor;
			estaBien = TRUE;
		}
		if(valor >0 && valor <= 99999){
			pRegistrarasintomatico_1_arg->id=valor;
			estaBien = TRUE;
		}
		

	}while(estaBien == FALSE);

	do{
		printf("\nDigite direccion: ");
		scanf("%s", &pruebadireccion);
		tamanio = strlen(pruebadireccion);
		if(tamanio <= 31){
			strcpy(pRegistrarasintomatico_1_arg->direccion, pruebadireccion);
			retorno=0;
		}

	}while(tamanio > 31);

	return retorno;
 }